build:
	@dune build --profile release

time day: build
	@time ./_build/default/bin/day{{day}}.exe

run day:
	@dune exec day{{day}} --profile=release

watch day:
	@dune exec day{{day}} --watch --profile=release
